config/routes.rb
Rails.application.routes.draw do
  resources :villas
  resources :globals
  resources :facilities
  resources :contacts
  resources :abouts
  resources :features
  devise_for :users
  resources :welcomes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcomes#index"
end

app/models/villa.rb
class Villa < ApplicationRecord
end

app/controllers/villas_controller.rb
class VillasController < ApplicationController
  before_action :set_villa, only: [:show, :edit, :update, :destroy]
  layout  "sublayout"

  # GET /villas
  # GET /villas.json
  def index
    @villas = Villa.all
  end

  # GET /villas/1
  # GET /villas/1.json
  def show
  end

  # GET /villas/new
  def new
    @villa = Villa.new
  end

  # GET /villas/1/edit
  def edit
  end

  # POST /villas
  # POST /villas.json
  def create
    @villa = Villa.new(villa_params)

    respond_to do |format|
      if @villa.save
        format.html { redirect_to @villa, notice: 'Villa was successfully created.' }
        format.json { render :show, status: :created, location: @villa }
      else
        format.html { render :new }
        format.json { render json: @villa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /villas/1
  # PATCH/PUT /villas/1.json
  def update
    respond_to do |format|
      if @villa.update(villa_params)
        format.html { redirect_to @villa, notice: 'Villa was successfully updated.' }
        format.json { render :show, status: :ok, location: @villa }
      else
        format.html { render :edit }
        format.json { render json: @villa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villas/1
  # DELETE /villas/1.json
  def destroy
    @villa.destroy
    respond_to do |format|
      format.html { redirect_to villas_url, notice: 'Villa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_villa
      @villa = Villa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def villa_params
      params.require(:villa).permit(:name, :body, :subbody, :main_image, :thumb_image, :status)
    end
end

app/helpers/villas_helper.rb
module VillasHelper
end

app/views/villas/_form.html.erb
<%= form_with(model: villa, local: true) do |form| %>
  <% if villa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(villa.errors.count, "error") %> prohibited this villa from being saved:</h2>

      <ul>
        <% villa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :subbody %>
    <%= form.text_area :subbody %>
  </div>

  <div class="field">
    <%= form.label :main_image %>
    <%= form.text_field :main_image %>
  </div>

  <div class="field">
    <%= form.label :thumb_image %>
    <%= form.text_field :thumb_image %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/villas/_villa.html.erb
<div class="container-fluid">
</div>
<div class="container mt-5 mb-5" style="margin-top: 100px; margin-bottom: 250px"> 
      <div class="row">
          
      </div>
      <div class="row">
            <div class="col-sm-12 col-md-5 col-lg-5  float-sm-right">   
                  <div class="row mt-5">
                        <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  

                      
                              <%= image_tag 'diamond-poolvilla-pool-01.jpg', class: 'img-fluid' %>
                      
                        </div>
                        <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                              <%= image_tag('diamond-poolvilla-pool-02.jpg', class: "img-fluid") %>
                        </div>  
                        <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                              <%= image_tag('diamond-poolvilla-terrace.jpg', class: "img-fluid") %>
                        </div>  
                  </div>      

                  <div class="row mt-3"> 
                        <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                              <%= image_tag('diamond-poolvilla-bedroom-01.jpg', class: "img-fluid") %>
                        </div>
                        <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                              <%= image_tag('diamond-poolvilla-bedroom-02.jpg', class: "img-fluid") %>
                        </div>  
                        <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                              <%= image_tag('diamond-poolvilla-livingroom-01.jpg', class: "img-fluid") %>
                        </div>  
                  </div>

                  <div class="row mt-3 mb-5">
                        <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                              <%= image_tag('diamond-poolvilla-kitchen-01.jpg', class: "img-fluid") %>
                        </div>
                        <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                              <%= image_tag('diamond-poolvilla-kitchen-02.jpg', class: "img-fluid") %>
                        </div>  
                        <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                              <%= image_tag('diamond-poolvilla-restroom.jpg', class: "img-fluid") %>
                        </div>  
                  </div>
                    
            </div>
            <div class="col-sm-12 col-md-7 col-lg-7 float-sm-left">
                        <h1 class="featurette-heading pl-3"><%= villa.name %></h1>
                         <h2 class="text-muted pl-3"><%= villa.subtitle %></h2>
                        <div class="lead mt-3 pl-3">
                              <p>
                                    <%= villa.body %>
                              </p>

                              <p class="mt5">
                                    <%= villa.subbody %>
                              </p>
                              
                              <%= link_to 'Edit', edit_welcome_path(villa) %>
                              <%= link_to 'Destroy', villa, method: :delete, data: { confirm: 'Are you sure?' } %>
                       </div>
            </div>
      </div>
</div>






   
      <tr>
        <td><%= villa.name %></td>
        <td><%= villa.body %></td>
        <td><%= villa.subbody %></td>
        <td><%= villa.main_image %></td>
        <td><%= villa.thumb_image %></td>
        <td><%= villa.status %></td>
        <td><%= link_to 'Show', villa %></td>
        <td><%= link_to 'Edit', edit_villa_path(villa) %></td>
        <td><%= link_to 'Destroy', villa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%= link_to 'New Villa', new_villa_path %>
      </tr>
    <% end %>
  

app/views/villas/edit.html.erb
<h1>Editing Villa</h1>

<%= render 'form', villa: @villa %>

<%= link_to 'Show', @villa %> |
<%= link_to 'Back', villas_path %>

app/views/villas/index.html.erb
<div stle="background-color: #eaeaea">
  <div class="container">
    <h1 class="featurette-heading">Stay with us</h1>
     </div>
    <hr class="featurette-divider">
</div>
<div class="container-fluid">
</div>
<div class="container mt-5 mb-5" style="margin-top: 100px; margin-bottom: 250px"> 
       <% @villas.each do |villa| %>
            <div class="row">
                  <div class="col-sm-12 col-md-5 col-lg-5  float-sm-right">   
                        <div class="row mt-5">
                              <div class="col-sm-12 col-md-4 col-lg-4 mt-1">         
                                    <%= image_tag 'diamond-poolvilla-pool-01.jpg', class: 'img-fluid' %> 
                              </div>
                              <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                                    <%= image_tag('diamond-poolvilla-pool-02.jpg', class: "img-fluid") %>
                              </div>  
                              <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                                    <%= image_tag('diamond-poolvilla-terrace.jpg', class: "img-fluid") %>
                              </div>  
                        </div>      

                        <div class="row mt-3"> 
                              <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                                    <%= image_tag('diamond-poolvilla-bedroom-01.jpg', class: "img-fluid") %>
                              </div>
                              <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                                    <%= image_tag('diamond-poolvilla-bedroom-02.jpg', class: "img-fluid") %>
                              </div>  
                              <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                                    <%= image_tag('diamond-poolvilla-livingroom-01.jpg', class: "img-fluid") %>
                              </div>  
                        </div>

                        <div class="row mt-3 mb-5">
                              <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                                    <%= image_tag('diamond-poolvilla-kitchen-01.jpg', class: "img-fluid") %>
                              </div>
                              <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                                    <%= image_tag('diamond-poolvilla-kitchen-02.jpg', class: "img-fluid") %>
                              </div>  
                              <div class="col-sm-12 col-md-4 col-lg-4 mt-1">  
                                    <%= image_tag('diamond-poolvilla-restroom.jpg', class: "img-fluid") %>
                              </div>  
                        </div>
                          
                  </div>
                  <div class="col-sm-12 col-md-7 col-lg-7 float-sm-left">
                      
                              <h2 class="featurette-heading pl-3"><%= villa.name %></h2>
                              <div class="lead mt-3 pl-3">
                                    <p>
                                          <%= villa.body %>
                                    </p>

                                    <p class="mt5">
                                          <%= villa.subbody %>
                                    </p>
                                    
                                    <%= link_to 'Edit', edit_welcome_path(villa) %>
                                    <%= link_to 'Destroy', villa, method: :delete, data: { confirm: 'Are you sure?' } %>
                            </div>
                  </div>

                  <%= link_to 'Edit', edit_villa_path(villa) %>
                  <%= link_to 'Destroy', villa, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <%= link_to 'New Villa', new_villa_path %>
            <% end %>
      </div>


       <div class="row"> 
        <div class="col-sm-12 col-md-6 col-lg-6 p-3 ">
          <h4 class="featurette-heading text-muted">Amenities</h4>
           <hr class="featurette-divider">
            
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 p-3 ">
          <h4 class="featurette-heading text-muted">Facities</h4>
           <hr class="featurette-divider">
        </div>
      </div>

      <div class="row"> 
        <div class="col-sm-12">
          <h4 class="featurette-heading text-muted">Room Rate</h4>
           <hr class="featurette-divider">   
        </div>
      </div>
</div>






   
  

app/views/villas/new.html.erb
<h1>New Villa</h1>

<%= render 'form', villa: @villa %>

<%= link_to 'Back', villas_path %>

app/views/villas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @villa.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @villa.body %>
</p>

<p>
  <strong>Subbody:</strong>
  <%= @villa.subbody %>
</p>

<p>
  <strong>Main image:</strong>
  <%= @villa.main_image %>
</p>

<p>
  <strong>Thumb image:</strong>
  <%= @villa.thumb_image %>
</p>

<p>
  <strong>Status:</strong>
  <%= @villa.status %>
</p>

<%= link_to 'Edit', edit_villa_path(@villa) %> |
<%= link_to 'Back', villas_path %>