config/routes.rb
Rails.application.routes.draw do
  resources :villas
  resources :globals
  resources :facilities
  resources :contacts
  resources :abouts
  resources :features
  devise_for :users
  resources :welcomes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcomes#index"
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/models/feature.rb
class Feature < ApplicationRecord
end

app/models/global.rb
class Global < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/villa.rb
class Villa < ApplicationRecord
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]
  layout  "sublayout"
  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
    @features = Feature.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:title, :subtitle, :body, :main_img, :thumb_img, :status)
    end
end

app/controllers/villas_controller.rb
class VillasController < ApplicationController
  before_action :set_villa, only: [:show, :edit, :update, :destroy]
  layout  "sublayout"

  # GET /villas
  # GET /villas.json
  def index
    @villas = Villa.all
  end

  # GET /villas/1
  # GET /villas/1.json
  def show
  end

  # GET /villas/new
  def new
    @villa = Villa.new
  end

  # GET /villas/1/edit
  def edit
  end

  # POST /villas
  # POST /villas.json
  def create
    @villa = Villa.new(villa_params)

    respond_to do |format|
      if @villa.save
        format.html { redirect_to @villa, notice: 'Villa was successfully created.' }
        format.json { render :show, status: :created, location: @villa }
      else
        format.html { render :new }
        format.json { render json: @villa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /villas/1
  # PATCH/PUT /villas/1.json
  def update
    respond_to do |format|
      if @villa.update(villa_params)
        format.html { redirect_to @villa, notice: 'Villa was successfully updated.' }
        format.json { render :show, status: :ok, location: @villa }
      else
        format.html { render :edit }
        format.json { render json: @villa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villas/1
  # DELETE /villas/1.json
  def destroy
    @villa.destroy
    respond_to do |format|
      format.html { redirect_to villas_url, notice: 'Villa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_villa
      @villa = Villa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def villa_params
      params.require(:villa).permit(:name, :body, :subbody, :main_image, :thumb_image, :status)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def copyright_helper name = ''
        F2ViewTool::Renderer.copyright "#{name}", 'All rights reserved'
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/helpers/villas_helper.rb
module VillasHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diamond Poolvilla Koh Samui Thailand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/navbar"%>
      <%= render "partials/banner" %>
      <div class="container-fluid">
        <%= render "partials/alert_notice" %>
        <%= yield %>
      </div>
      <%= render 'partials/social' %>
      <%= render 'partials/maps' %>
      <%= render 'partials/footer' %>
      <%= render 'partials/js'%>

  </body>
</html>

app/views/layouts/sublayout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diamond Poolvilla Koh Samui Thailand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/navbar"%>
      <div class="container-fluid mt-5 mb-5 pt-5 pb-5 ">
        <%= render "partials/alert_notice" %>
        <%= yield %>
      </div>
      <%= render 'partials/social' %>
      <%= render 'partials/maps' %>
      <%= render 'partials/footer' %>
      <%= render 'partials/js'%>

  </body>
</html>

app/views/partials/_alert_notice.html.erb
<div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
</div>

app/views/partials/_banner.html.erb
<div class="head-banner">
    <%= image_tag('main-banner.png', class: "img-fluid") %>
    <%# <%= render 'partials/feature'%>
</div>

app/views/partials/_contact_mail_form.html.erb
<h2 class="text-muted">Enquiry Form</h2>
<%= form_with() do |form| %>
  <div class="form-group">
    <%= form.label :Name %>
    <%= form.text_field :name, class: 'form-control', rows: 8 %>
  </div>

  <div class="form-group">
    <%= form.label :Email %>
    <%= form.text_field :email, class: 'form-control', rows: 8 %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 8 %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/partials/_feature.html.erb
<div class="row feature-banner">
         <% @features.each do |feature| %>
         <div class="col-sm-6 col-md-3 col-lg-3">
             <div class="text-center p-4 mt-5">
                  <%= fa_icon "#{feature.thumb_img}", style: "font-size: 5.0rem" %>
               </div>
            <div class="card m-1 d-block", style="height: 380px">
               <div class="card-title text-center pt-4">
                  <h2><%= feature.title %> </h2>
               </div>
               <div class="card-body lead text-center">
                  <%= feature.body %>
               </div>
            </div>
            <%# <% if logged_in?(:admin)%> 
            <div class="text-right">
               <%= link_to 'Edit', edit_feature_path(feature), class: "btn btn-secondary" %>
               <%= link_to 'Destroy', feature, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary" %>
            </div>
            <%# <%end%> 
         </div>
     <% end %>       
</div>
</div>

app/views/partials/_footer.html.erb
<div class="container-fluid footer-main">
    <div class="container">
      <div class="row">
          <div class="col-sm-12 col-md-3 col-lg-3 text-left">
            <%= image_tag('diamond-logo-250x250.png') %>
          </div>
          <div class="col-sm-12 col-md-3 col-lg-3 text-right p-4">
              <h5 class="text-uppercase">Links</h5>
              <hr class="featurette-divider">
              <ul class="list-unstyled text-small">
                    <%= link_to "Welcome", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Villas", abouts_path, class:'text-muted' %></li>
                    <li><%= link_to "Facilities", facilities_path, class:'text-muted' %></li>
                    <li><%= link_to "About", abouts_path, class:'text-muted' %></li>
                    <%# <%= link_to "The Artists", profiles_path, class:'nav-link'  %> 
                    <%# <%= link_to "Guest Artists", profiles_path, class:'nav-link' %>
                    <%# <%= link_to "Blog", blogs_path, class:'nav-link' %>  
                    <li><%= link_to "Contact", contacts_path, class:'text-muted'%></li> 
                    <li><%= link_to "Term & Policies", contacts_path, class:'text-muted'%></li> 
            </ul>
          </div>

          <div class="col-sm-12 col-md-3 col-lg-3 text-right p-4">
            <h5 class="text-uppercase">Transfer</h5>
            <hr class="featurette-divider">
                 <ul class="list-unstyled text-small">
                    <%= link_to "Chaweng", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Bophut", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Lamai", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Hua Thanon", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Lipa Noi", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Nathon", root_path, class:'text-muted' %></li>
                    <%# <%= link_to "The Artists", profiles_path, class:'  %> 
                    <%# <%= link_to "Guest Artists", profiles_path, class:' %>
                    <%# <%= link_to "Blog", blogs_path, class:' %>  
                    <li><%= link_to "Maenam", root_path, class:'text-muted'%></li> 
                </ul>  
          </div>

          <div class="col-sm-12 col-md-3 col-lg-3 text-right p-4">
            <h5 class="text-uppercase">Where to go</h5>
            <hr class="featurette-divider">     
                <ul class="list-unstyled text-small">
                    <%= link_to "Chaweng Beach", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Big Budha", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Hinta Hinyai", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Tiger Zoo", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Fisherman Walking Street", root_path, class:'text-muted' %></li>
                    <li><%= link_to "Namuang Water Fall", root_path, class:'text-muted' %></li>
                    <%# <%= link_to "The Artists", profiles_path, class:'  %> 
                    <%# <%= link_to "Guest Artists", profiles_path, class:' %>
                    <%# <%= link_to "Blog", blogs_path, class:' %>  
                    <li><%= link_to "Maenam Beach", root_path, class:'text-muted'%></li> 
                </ul>  
          </div>
      </div>
    </div>
</div>

<div class="row">
      <div class="container mt-5">
        <p class="float-right"><a href="#" class="text-dark">Back to top</a></p>
        <p><%= copyright_helper 'Diamond Pool Villa Samui' %></p>
      </div>
</div>


 

app/views/partials/_js.html.erb
      <div>
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
                          
      </div>

app/views/partials/_maps.html.erb
<div class="pt-0">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15738.076127420676!2d100.0664818!3d9.5504478!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xa598a5fb770ee6b4!2sDiamond%20Pool%20Villa%20Samui!5e0!3m2!1sen!2sth!4v1570524341231!5m2!1sen!2sth" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="true"></iframe>
</div>

app/views/partials/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
        <div class="container">
          <a class="navbar-brand featurette-heading" href="/welcomes" style="font-size:1.5em"><b><span style="color: #9d1e63">Diamond</span><span class="text-warning">PoolVilla</span></b></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                  <%= link_to "Welcome", root_path, class:'nav-link' %>
                  <%= link_to "Villas", villas_path, class:'nav-link' %>
                  <%# <%= link_to "Facilities", facilities_path, class:'nav-link' %>
                  <%# <%= link_to "About", abouts_path, class:'nav-link' %>
                  <%# <%= link_to "The Artists", profiles_path, class:'nav-link'  %> 
                  <%# <%= link_to "Guest Artists", profiles_path, class:'nav-link' %>
                  <%# <%= link_to "Blog", blogs_path, class:'nav-link' %>  
                  <%= link_to "Contact", contacts_path, class:'nav-link'     %>   
               </ul> 
                <ul class="navbar-nav">            
                              <a href="https://www.facebook.com/diamondpoolvillakohsamui", target="_blank"><%= fa_icon "facebook", style: "font-size: 1.5rem", class: 'nav-link' %> </a>
                              <a href="#" ><%= fa_icon "instagram", style: "font-size: 1.5rem", class: 'nav-link' %></a>
                              <a href="mailto:diamondvilla.samui@gmail.com" ><%= fa_icon "envelope", style: "font-size: 1.5rem", class: 'nav-link' %></a>
                              <a href="tel:+66952524878" > <%= fa_icon "phone", style: "font-size: 1.5rem", class: 'nav-link ml-2' %></a>
                          <div class="pl-3">
                          </div>
                </ul>
          </div>
        </div>
  </nav>
</header>

app/views/partials/_social.html.erb
<div class="bg-light text-dark mt-5 pt-5 pb-5">
    <div class="container pb-5">
    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-4">
            <h1 class="text-muted">Connect Us</h1>
        </div>
       
        <div class="col-sm-12 col-md-3 col-lg-6">
            <a href="https://www.facebook.com/diamondpoolvillakohsamui", target="_blank"><%= fa_icon "facebook", style: "font-size: 3.0rem", class: 'nav-link' %></a>

            <a href="#" ><%= fa_icon "instagram", style: "font-size: 3.0rem", class: 'nav-link' %></a>

            <a href="mailto:diamondvilla.samui@gmail.com" ><%= fa_icon "envelope", style: "font-size: 3.0rem", class: 'nav-link' %></a>
            
            <span class="lead text-right"><a href="tel:+66952524878" ><%= fa_icon "phone", style: "font-size: 3.0rem", class: 'nav-link ml-2' %></span></a>
         </div>
    </div>
</div>