config/routes.rb
Rails.application.routes.draw do
  resources :villas
  resources :globals
  resources :facilities
  resources :contacts
  resources :abouts
  resources :features
  devise_for :users
  resources :welcomes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcomes#index"
end

app/models/global.rb
class Global < ApplicationRecord
end

app/controllers/globals_controller.rb
class GlobalsController < ApplicationController
  before_action :set_global, only: [:show, :edit, :update, :destroy]

  # GET /globals
  # GET /globals.json
  def index
    @globals = Global.all
  end

  # GET /globals/1
  # GET /globals/1.json
  def show
  end

  # GET /globals/new
  def new
    @global = Global.new
  end

  # GET /globals/1/edit
  def edit
  end

  # POST /globals
  # POST /globals.json
  def create
    @global = Global.new(global_params)

    respond_to do |format|
      if @global.save
        format.html { redirect_to @global, notice: 'Global was successfully created.' }
        format.json { render :show, status: :created, location: @global }
      else
        format.html { render :new }
        format.json { render json: @global.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /globals/1
  # PATCH/PUT /globals/1.json
  def update
    respond_to do |format|
      if @global.update(global_params)
        format.html { redirect_to @global, notice: 'Global was successfully updated.' }
        format.json { render :show, status: :ok, location: @global }
      else
        format.html { render :edit }
        format.json { render json: @global.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /globals/1
  # DELETE /globals/1.json
  def destroy
    @global.destroy
    respond_to do |format|
      format.html { redirect_to globals_url, notice: 'Global was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_global
      @global = Global.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def global_params
      params.require(:global).permit(:name_first, :name_last, :slogan, :title, :desc, :logo, :status, :keywords)
    end
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/views/globals/_form.html.erb
<%= form_with(model: global, local: true) do |form| %>
  <% if global.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(global.errors.count, "error") %> prohibited this global from being saved:</h2>

      <ul>
        <% global.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name_first %>
    <%= form.text_field :name_first %>
  </div>

  <div class="field">
    <%= form.label :name_last %>
    <%= form.text_field :name_last %>
  </div>

  <div class="field">
    <%= form.label :slogan %>
    <%= form.text_field :slogan %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.text_field :logo %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :keywords %>
    <%= form.text_area :keywords %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/globals/edit.html.erb
<h1>Editing Global</h1>

<%= render 'form', global: @global %>

<%= link_to 'Show', @global %> |
<%= link_to 'Back', globals_path %>

app/views/globals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Globals</h1>

<table>
  <thead>
    <tr>
      <th>Name first</th>
      <th>Name last</th>
      <th>Slogan</th>
      <th>Title</th>
      <th>Desc</th>
      <th>Logo</th>
      <th>Status</th>
      <th>Keywords</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @globals.each do |global| %>
      <tr>
        <td><%= global.name_first %></td>
        <td><%= global.name_last %></td>
        <td><%= global.slogan %></td>
        <td><%= global.title %></td>
        <td><%= global.desc %></td>
        <td><%= global.logo %></td>
        <td><%= global.status %></td>
        <td><%= global.keywords %></td>
        <td><%= link_to 'Show', global %></td>
        <td><%= link_to 'Edit', edit_global_path(global) %></td>
        <td><%= link_to 'Destroy', global, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Global', new_global_path %>

app/views/globals/new.html.erb
<h1>New Global</h1>

<%= render 'form', global: @global %>

<%= link_to 'Back', globals_path %>

app/views/globals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name first:</strong>
  <%= @global.name_first %>
</p>

<p>
  <strong>Name last:</strong>
  <%= @global.name_last %>
</p>

<p>
  <strong>Slogan:</strong>
  <%= @global.slogan %>
</p>

<p>
  <strong>Title:</strong>
  <%= @global.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @global.desc %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @global.logo %>
</p>

<p>
  <strong>Status:</strong>
  <%= @global.status %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @global.keywords %>
</p>

<%= link_to 'Edit', edit_global_path(@global) %> |
<%= link_to 'Back', globals_path %>