config/routes.rb
Rails.application.routes.draw do
  resources :villas
  resources :globals
  resources :facilities
  resources :contacts
  resources :abouts
  resources :features
  devise_for :users
  resources :welcomes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcomes#index"
end

app/models/about.rb
class About < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]
  layout  "sublayout"
  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
    @features = Feature.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:title, :subtitle, :body, :main_img, :thumb_img, :status)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= form_with(model: about, local: true) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
        <% about.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :main_img %>
    <%= form.text_field :main_img %>
  </div>

  <div class="field">
    <%= form.label :thumb_img %>
    <%= form.text_field :thumb_img %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<div stle="background-color: #eaeaea">
  <div class="container">
    <h1 class="featurette-heading">About Us</h1>
     </div>
    <hr class="featurette-divider">
</div>

<div class="container">
    <% @abouts.each do |about| %>
      <div class="row">
          
          <div class="col-sm-12 col-md-6 col-sm-6">
            <p class="text-muted"><%= about.title %></p>
            <p><%= about.subtitle %></p>
            <p class="lead"><%= about.body %></p>
            <p><%= about.main_img %></p>
            <p><%= about.thumb_img %></p>
            <p><%= about.status %></p>
            <p><%= link_to 'Show', about %>
            <%= link_to 'Edit', edit_about_path(about) %>
            <%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          </div>

          <div class="col-sm-12 col-md-6 col-sm-6">
            <%= image_tag('') %>
          </div>
      </div>

    <% end %>
<%= link_to 'New About', new_about_path %>
</div>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @about.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @about.subtitle %>
</p>

<p>
  <strong>Body:</strong>
  <%= @about.body %>
</p>

<p>
  <strong>Main img:</strong>
  <%= @about.main_img %>
</p>

<p>
  <strong>Thumb img:</strong>
  <%= @about.thumb_img %>
</p>

<p>
  <strong>Status:</strong>
  <%= @about.status %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>